PreOrderApp/Controllers/PaymentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PreOrderApp.Models;
using WebMatrix.WebData;

namespace PreOrderApp.Controllers
{
	public class PaymentController : Controller
	{
		private PreOrderAppEntities _db = new PreOrderAppEntities();

		
		public ActionResult Index()
		{
			IOrderedQueryable<Payment> orderByDescending = _db.Payments.OrderByDescending(payment => payment.Date);
			IQueryable<Payment> queryable = orderByDescending.Include("MenuItem");

			if (Roles.IsUserInRole("Customer"))
			{
				return View(queryable.Where(payment => payment.UserId == WebSecurity.CurrentUserId));
			}
			else
			{
				return View(queryable.Where(payment => payment.MenuItem.UserId == WebSecurity.CurrentUserId));	
			}

		}

	}
}

PreOrderApp/Controllers/SelectPaymentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Objects;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PreOrderApp.Models;
using WebMatrix.WebData;

namespace PreOrderApp.Controllers
{
	public class SelectPaymentController : Controller
	{
		private PreOrderAppEntities _database = new PreOrderAppEntities();

		
		public ActionResult Index()
		{
			ObjectQuery<MenuItem> objectQuery = _database.MenuItems.Include("UserProfile");
			return View(objectQuery.Where(menuItem => menuItem.Active == true));

		}

		public ActionResult SelectMenu(int id)
		{
			MenuItem menuItem = _database.MenuItems.Single(menu => menu.Id == id);
			UserProfile restaurant = _database.UserProfiles.Where(user => user.UserId == menuItem.UserId).FirstOrDefault();
			List<string> reservations=new List<string>();
			if(restaurant.ReservationStart.HasValue)
			{
				bool isIn = true;
				string time = string.Format("{0}:{1}", restaurant.ReservationStart.Value.ToString("hh"), restaurant.ReservationStart.Value.ToString("mm"));
				TimeSpan start = restaurant.ReservationStart.Value;
				while (isIn)
				{
					time = string.Format("{0}:{1}", start.ToString("hh"), start.ToString("mm"));
					reservations.Add(time);
					start=start.Add(TimeSpan.FromMinutes(restaurant.ReservationDuration.Value));
					isIn = (start <= restaurant.ReservationEnd.Value);
				}
			}
			else
			{
				reservations.AddRange(new string[]{"11:30", "12:00", "12:30", "13:00", "13:30", "14:00"});
			}
			//ViewBag.ReservationHour = new SelectList(reservations);
			List<SelectListItem> selectListItems = new List<SelectListItem>();
			foreach (string reservation in reservations)
			{
				selectListItems.Add(new SelectListItem(){Text=reservation, Value = reservation});
			}
			MenuItemModel menuItemModel = new MenuItemModel();
			menuItemModel.Id = menuItem.Id;
			menuItemModel.Price = menuItem.Price;
			menuItemModel.Name = menuItem.Name;
			menuItemModel.ReservationHour = "12:00";
			menuItemModel.RestaurantReservationHours = selectListItems;
			return View(menuItemModel);
		}

		//
		// POST: /Registru/Edit/5

		[HttpPost]
		public ActionResult SelectMenu(MenuItemModel menuItem)
		{
			try
			{
				if (ModelState.IsValid)
				{
					MenuItem item = _database.MenuItems.Single(menu => menu.Id == menuItem.Id);

					
					Payment payment = _database.Payments.CreateObject();
					payment.MenuItemId = item.Id;
					payment.UserId = WebSecurity.CurrentUserId;
					payment.Date = DateTime.Now;
					payment.RestaurantID = item.UserId;
					payment.ReservationHour = menuItem.ReservationHour;
					_database.Payments.Attach(payment);
					_database.ObjectStateManager.ChangeObjectState(payment, EntityState.Added);
					_database.SaveChanges();
					return RedirectToAction("Index","Payment");
				}
				return View(menuItem);
			}
			catch (OptimisticConcurrencyException optimisticConcurrencyException)
			{
				_database.MenuItems.Detach(menuItem);
				ModelState.AddModelError("", "Optimistic Concurrency Exception occurred. Save Again to override");

			}
			catch (Exception ex)
			{
				ModelState.AddModelError("", "See exception and inner exception");
			}

			return View(menuItem);
		}


	}
}

PreOrderApp/Views/Shared/_Layout.cshtml
@using PreOrderApp
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - PreOrder App</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
					<img  src="../../Images/logo.jpg" alt="logo"/>
                </div>
                <div class="float-right">
					<section id="login">
						@Html.Partial("_LoginPartial")
					</section>
					<nav>
						<ul id="menu">
							@{
								object customers = this.Session["Customers"];
								object restaurants = this.Session["Restaurants"];
								string nrCustomers = (customers == null) ? "0" : customers.ToString();
								string nrRestaurants = (restaurants == null) ? "0" : restaurants.ToString();
							}

							<li style="color: red">@nrCustomers Customers and @nrRestaurants Restaurants !!!</li>
							<li>@Html.ActionLink("About", "About", "Home")</li>
							<li>@Html.ActionLink("Contact", "Contact", "Home")</li>
							@{
								if(Roles.IsUserInRole("Administrator"))
								{
									<li>@Html.ActionLink("Registered Restaurants", "RegisteredRestaurants", "Home")</li>	
									<li>@Html.ActionLink("Customers", "RegisteredCustomers", "Home")</li>	
								}
							}
							@{
								if(Roles.IsUserInRole("Restaurant"))
								{
									<li>@Html.ActionLink("Menues", "Index", "Restaurant")</li>	
									<li>@Html.ActionLink("Payments", "Index", "Payment")</li>	
								}
							}
							@{
								if(Roles.IsUserInRole("Customer"))
								{
									<li>@Html.ActionLink("Payments", "Index", "Payment")</li>
									<li>@Html.ActionLink("Menu Offers", "Index", "SelectPayment")</li>		
								}
							}
						</ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - PreOrder App</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>